version: '3.9'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    working_dir: /home/node/app
    command: dev
    tty: true
    stdin_open: true
    environment:
      - MYSQLHOST_CONTAINER=db
    volumes: 
      - .:/home/node/
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=goodboy
      - MYSQL_DATABASE=goodboy
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
