FROM node:16.14-alpine
RUN mkdir -p /home/node/app && chown -R node:node /home/node/app
WORKDIR /home/node/app
COPY --chown=node:node package*.json .
USER node
RUN yarn install
COPY --chown=node:node . .
# RUN chmod -R 755 /home/node/app
EXPOSE 3002
ENTRYPOINT [ "npm", "run", "dev" ]